# Generated by Django 6.0.3 on 2026-03-16 15:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_last4', models.CharField(max_length=4)),
                ('holder_name', models.CharField(max_length=100)),
                ('expiry', models.CharField(max_length=5)),
                ('card_type', models.CharField(default='VISA', max_length=20)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('FROZEN', 'Frozen'), ('BLOCKED', 'Blocked')], default='ACTIVE', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField()),
                ('location', models.CharField(blank=True, default='Unknown', max_length=200)),
                ('merchant', models.CharField(blank=True, default='Unknown', max_length=200)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('prediction', models.CharField(choices=[('Legitimate', 'Legitimate'), ('Fraud', 'Fraud'), ('Pending', 'Pending')], default='Pending', max_length=20)),
                ('fraud_probability', models.FloatField(default=0.0)),
                ('raw_features', models.JSONField(blank=True, default=dict)),
                ('alert_sent', models.BooleanField(default=False)),
                ('card', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='fraud_app.card')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='FraudAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved', models.BooleanField(default=False)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('transaction', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='alert', to='fraud_app.transaction')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
