# Generated by Django 6.0.3 on 2026-03-17 03:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fraud_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='shap_explanation',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.CreateModel(
            name='MerchantBlacklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('merchant_name', models.CharField(max_length=200, unique=True)),
                ('reason', models.TextField(blank=True, default='Flagged by admin')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('added_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Merchant Blacklist',
                'verbose_name_plural': 'Merchant Blacklist',
                'ordering': ['-created_at'],
            },
        ),
    ]
